-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Apple Computer Inc Color LCD",
  mode = "2880x1800@60.00",
  position = "1777x1152",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
