-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
  input = {
    kb_layout = "se",
    kb_variant = "mac",
  },
})

