-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Apple Computer Inc Color LCD",
  mode = "2880x1800@60.00",
  position = "1748x1152",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-1",
  mode = "2560x1440@60.00",
  position = "1440x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-2",
  disabled = true,
})
