-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Apple Computer Inc iMac 99C681F5D4234",
  mode = "3840x2160@60.00",
  position = "0x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-2",
  mode = "3840x2160@60.00",
  position = "3072x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-3",
  mode = "2560x2880@60.00",
  position = "6144x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Apple Computer Inc iMac 99C681F5D4234", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Apple Computer Inc iMac 99C681F5D4234" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Apple Computer Inc iMac 99C681F5D4234" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Apple Computer Inc iMac 99C681F5D4234" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Apple Computer Inc iMac 99C681F5D4234" })
hl.workspace_rule({ workspace = "6", monitor = "DP-2", default = true })
hl.workspace_rule({ workspace = "7", monitor = "DP-2" })
hl.workspace_rule({ workspace = "8", monitor = "DP-2" })
hl.workspace_rule({ workspace = "9", monitor = "DP-2" })
hl.workspace_rule({ workspace = "10", monitor = "DP-2" })
